name: FCS Kiosk
description: FCS Welcome Kiosk
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables"]
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]

baseurl: '' #/cs3025-prototype
